<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-14T12:15:17 IST" name="Suite" finished-at="2023-02-14T12:16:54 IST" duration-ms="97023">
    <groups>
    </groups>
    <test started-at="2023-02-14T12:15:17 IST" name="Test" finished-at="2023-02-14T12:16:54 IST" duration-ms="97023">
      <class name="Tests.LoginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:15:17 IST" name="setUp" finished-at="2023-02-14T12:15:55 IST" duration-ms="38045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLoginPageWithInvalidCredentials(java.lang.String,java.lang.String)[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:15:55 IST" name="verifyLoginPageWithInvalidCredentials" data-provider="getCredentials" finished-at="2023-02-14T12:16:07 IST" duration-ms="11182" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageWithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:07 IST" name="tearDown" finished-at="2023-02-14T12:16:08 IST" duration-ms="1830" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:08 IST" name="setUp" finished-at="2023-02-14T12:16:17 IST" duration-ms="8962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLoginPageWithInvalidCredentials(java.lang.String,java.lang.String)[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:17 IST" name="verifyLoginPageWithInvalidCredentials" data-provider="getCredentials" finished-at="2023-02-14T12:16:19 IST" duration-ms="1790" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required1232]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required1232]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Tests.LoginPageTest.verifyLoginPageWithInvalidCredentials(LoginPageTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageWithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:20 IST" name="tearDown" finished-at="2023-02-14T12:16:21 IST" duration-ms="1310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:21 IST" name="setUp" finished-at="2023-02-14T12:16:34 IST" duration-ms="12854" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLoginPageWithInvalidCredentials(java.lang.String,java.lang.String)[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:34 IST" name="verifyLoginPageWithInvalidCredentials" data-provider="getCredentials" finished-at="2023-02-14T12:16:36 IST" duration-ms="2138" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required1232]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required1232]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Tests.LoginPageTest.verifyLoginPageWithInvalidCredentials(LoginPageTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageWithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:36 IST" name="tearDown" finished-at="2023-02-14T12:16:37 IST" duration-ms="979" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:37 IST" name="setUp" finished-at="2023-02-14T12:16:46 IST" duration-ms="8803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLoginPageWithValidCredentials()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:46 IST" name="verifyLoginPageWithValidCredentials" finished-at="2023-02-14T12:16:54 IST" duration-ms="7612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.LoginPageTest@30c93896]" started-at="2023-02-14T12:16:54 IST" name="tearDown" finished-at="2023-02-14T12:16:54 IST" duration-ms="755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
